### ISSUE TITLE
Files missing on master

### ISSUE THREAD

**Issue by naychrist** [bakercp/ofxPointer#2]
Hi there,
just tried to compile this but seems some files didn't get added in the last merge to master such as `PointerEventArgs.h`

**Comment by bakercp** [comment]
Hm.  I'll check it out!

**Comment by bakercp** [comment]
Ah, sorry -- `PointerEventArgs` recently became `PointerEvent` -- this was updated in the example, but not in the README.md.  Could you try the example from master and reopen this issue if 14ce946b3e49887d9f41b67ea1e32e22346deb80 didn't fix it?

**Comment by bakercp** [comment]
Actually just noticed that an old .cpp file hadn't been deleted!  I fixed it with 19eec7d00b6248910758c057af710c85b809cd26.
