### ISSUE TITLE
Error compile with of 0.97

### ISSUE THREAD

**Issue by aletes67** [bakercp/ofxPointer#3]
I'm trying to use this addon which could be useful for me, but I get these errors.

Compiling /mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/src/PointerEvents.cpp
g++ -c -O3 -DNDEBUG -march=native -mtune=native -Wall -std=c++14 -DGCC_HAS_REGEX -DOF_USING_GTK -DOF_USING_GTK -DOF_USING_MPG123  -pthread -I/usr/include/gstr
eamer-1.0 -I/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include -I/usr/include/AL -I/usr/include/libdrm -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/u
sr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/
mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/
usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include
/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/fmodex/include -I/mnt/dati/code
/of_v0.9.7_linux64_release/libs/glfw/include -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/glfw/include/GLFW -I/mnt/dati/code/of_v0.9.7_linux64_release/libs
/kiss/include -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/poco/include -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/tess2/include -I/mnt/dati/code/of_v
0.9.7_linux64_release/libs/utf8cpp/include -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/utf8cpp/include/utf8 -I/mnt/dati/code/of_v0.9.7_linux64_release/lib
s/openFrameworks -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworks/graphics -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworks/app -I
/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworks/types -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworks/math -I/mnt/dati/code/of_v0.
9.7_linux64_release/libs/openFrameworks/sound -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworks/utils -I/mnt/dati/code/of_v0.9.7_linux64_release/
libs/openFrameworks/gl -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworks/communication -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFramew
orks/video -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworks/3d -I/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworks/events -I/mnt/dati
/code/of_v0.9.7_linux64_release/addons/ofxPointer/src -I/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs -I/mnt/dati/code/of_v0.9.7_linux64_rel
ease/addons/ofxPointer/libs/ofxPointer -I/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include -I/mnt/dati/code/of_v0.9.7_linux64
_release/addons/ofxPointer/libs/ofxPointer/include/ofx -I/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/src -I/mnt/dati/code/of_v0
.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include -I/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx -MMD -
MP -MF /mnt/dati/code/of_v0.9.7_linux64_release/addons/obj/linux64/Release/ofxPointer/libs/ofxPointer/src/PointerEvents.d -MT /mnt/dati/code/of_v0.9.7_linux64
_release/addons/obj/linux64/Release/ofxPointer/libs/ofxPointer/src/PointerEvents.o -o /mnt/dati/code/of_v0.9.7_linux64_release/addons/obj/linux64/Release/ofxP
ointer/libs/ofxPointer/src/PointerEvents.o -c /mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/src/PointerEvents.cpp
In file included from /mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/src/PointerEvents.cpp:8:0:
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:112:21: error: ‘glm’ has not been declared
 class Point: public glm::vec3
                     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:112:26: error: expected ‘{’ before ‘vec3’
 class Point: public glm::vec3
                          ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:114:1: error: expected primary-expression before ‘publi
c’
 public:
 ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:114:1: error: expected ‘}’ before ‘public’
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:114:1: error: expected ‘,’ or ‘;’ before ‘public’
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:120:11: error: expected unqualified-id before ‘const’
     Point(const glm::vec3& position);
           ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:120:11: error: expected ‘)’ before ‘const’
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:125:11: error: expected unqualified-id before ‘const’
     Point(const glm::vec3& position, const PointShape& shape);
           ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:125:11: error: expected ‘)’ before ‘const’
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:132:11: error: expected unqualified-id before ‘const’
     Point(const glm::vec3& position, float pressure, float tiltX, float tiltY);
           ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:132:11: error: expected ‘)’ before ‘const’
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:138:11: error: expected unqualified-id before ‘const’
     Point(const glm::vec3& position, const PointShape& shape, float pressure);
           ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:138:11: error: expected ‘)’ before ‘const’
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:149:11: error: expected unqualified-id before ‘const’
     Point(const glm::vec3& position,
           ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:149:11: error: expected ‘)’ before ‘const’
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:159:20: error: declaration of ‘~ofx::Point’ as non-memb
er
     virtual ~Point();
                    ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:172:11: error: ‘glm’ does not name a type
     const glm::vec3& absolutePosition() const;
           ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:181:22: error: non-member function ‘float ofx::pressure
()’ cannot have cv-qualifier
     float pressure() const;
                      ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:190:32: error: non-member function ‘float ofx::tangenti
alPressure()’ cannot have cv-qualifier
     float tangentialPressure() const;
                                ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:202:22: error: non-member function ‘float ofx::rotation
()’ cannot have cv-qualifier
     float rotation() const;
                      ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:212:19: error: non-member function ‘float ofx::tiltX()’
 cannot have cv-qualifier
     float tiltX() const;
                   ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:222:19: error: non-member function ‘float ofx::tiltY()’
 cannot have cv-qualifier
     float tiltY() const;
                   ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:226:31: error: non-member function ‘const ofx::PointSha
pe& ofx::shape()’ cannot have cv-qualifier
     const PointShape& shape() const;
                               ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:228:1: error: expected unqualified-id before ‘private’
 private:
 ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:266:28: error: ‘Point’ does not name a type
                      const Point& point,
                            ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:285:5: error: ‘Point’ does not name a type
     Point point() const;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:449:5: error: ‘Point’ does not name a type
     Point _point;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:634:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _mouseMovedListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:637:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _mouseDraggedListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:640:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _mousePressedListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:643:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _mouseReleasedListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:647:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _touchUpListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:650:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _touchDownListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:653:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _touchMovedListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:656:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _touchDoubleTapListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:659:5: error: ‘ofEventListener’ does not name a type
     ofEventListener _touchCancelledListener;
     ^
/mnt/dati/code/of_v0.9.7_linux64_release/addons/ofxPointer/libs/ofxPointer/include/ofx/PointerEvents.h:698:1: error: expected declaration before ‘}’ token
 } // namespace ofx
 ^
/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:336: set di istruzioni per l'obiettivo "/mnt/da
ti/code/of_v0.9.7_linux64_release/addons/obj/linux64/Release/ofxPointer/libs/ofxPointer/src/PointerEvents.o" non riuscito
make[1]: *** [/mnt/dati/code/of_v0.9.7_linux64_release/addons/obj/linux64/Release/ofxPointer/libs/ofxPointer/src/PointerEvents.o] Errore 1
make[1]: uscita dalla directory "/mnt/dati/code/of_v0.9.7_linux64_release/apps/myApps/TouchTest"
/mnt/dati/code/of_v0.9.7_linux64_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: set di istruzioni per l'obiettivo "Release
" non riuscito
make: *** [Release] Errore 2

**Comment by bakercp** [comment]
`ofEventListener’ does not name a type` is because `ofEventListener’ is a new class in 0.10+.

Please see the https://github.com/bakercp/ofxPointer#compatibility README for which branch to try .  It sounds like you should be using the stable branch.

**Comment by aletes67** [comment]
I installed OF stable repo and ofxPointer stable and it worked. thank you
