### ISSUE TITLE
Listen event from specific interface

### ISSUE THREAD

**Issue by aletes67** [bakercp/ofxPointer#4]
Hello. I'm trying to "force" listen events from a specific interface (eg /dev/input/eventX). What is the most appropriate way to do this? thank you

**Comment by bakercp** [comment]
Currently there is no way to do this with ofxPointer as all linux events still come through GLFW on the desktop. While I have made custom listeners for iOS, I probably won't do that for the desktop and will (for now) just repackage the pointer information from GLFW and the other default windows. That said, I'd welcome more sophisticated pointer event input filtering!
